import { useMemo, useState } from "react";
import { demoExamples } from "./demoExamples.js";

const resultCards = [
  {
    label: "Approximate-hard ECC",
    value: "TPR > 0.96",
    detail: "Across k = 1, 2, 3 under delta = 20, while keeping FAR below 0.007.",
  },
  {
    label: "Localization coverage",
    value: "0.99 at k = 1",
    detail: "Candidate edit-location coverage remains near-perfect in the single-edit regime.",
  },
  {
    label: "Adaptive generation",
    value: "PPL 64.1 -> 23.6",
    detail: "Adaptive codeword completion reduces distortion under strong structural bias.",
  },
  {
    label: "LLM-guided sparse edits",
    value: "226 cases",
    detail: "Question-aware sparse edits generated from LFQA prompts and Qwen3-8B source answers.",
  },
];

const methodSteps = [
  {
    title: "ECC-constrained watermarking",
    text:
      "Generated tokens are mapped into structural bits through a vocabulary partition. " +
      "Each local block is encouraged to satisfy a joint VT and Hamming feasible codeword constraint.",
  },
  {
    title: "Boundary-aware block recovery",
    text:
      "A separate boundary-anchor bucket closes structural blocks, allowing the detector to parse edited text back into local watermark blocks.",
  },
  {
    title: "Post-edit decoding",
    text:
      "The detector globally parses the observed structural sequence and measures each parsed block's edit distance to the feasible ECC set.",
  },
  {
    title: "Localization signal",
    text:
      "Blocks whose distance exceeds a tolerance threshold are flagged as suspicious, and the decoder returns candidate edit locations inside those blocks.",
  },
];

const references = [
  "Kirchenbauer et al. Watermarking LLM-generated text. ICML, 2023.",
  "Zhao et al. Provable robust watermarking for AI-generated text. ICLR, 2024.",
  "Zhao et al. Efficiently identifying watermarked segments in mixed-source text. 2025.",
  "Pan et al. WaterSeeker: Efficient detection of watermarked segments. 2025.",
  "Levenshtein. Binary codes capable of correcting deletions, insertions, and reversals. 1966.",
  "Hamming. Error detecting and error correcting codes. 1950.",
];

function App() {
  return (
    <main>
      <Nav />
      <Hero />
      <Motivation />
      <Method />
      <Results />
      <InteractiveDemo />
      <Citation />
    </main>
  );
}

function Nav() {
  return (
    <nav className="nav">
      <a className="brand" href="#top">ECC Local Integrity</a>
      <div className="navLinks">
        <a href="#method">Method</a>
        <a href="#results">Results</a>
        <a href="#demo">Walkthrough</a>
        <a href="#citation">Citation</a>
      </div>
    </nav>
  );
}

function Hero() {
  return (
    <section id="top" className="hero">
      <div className="heroText">
        <p className="eyebrow">Paper companion site</p>
        <h1>Local Integrity Checking for Watermarked LLM Outputs via Error-Correcting Codes</h1>
        <p className="lead">
          We study how to detect and localize sparse post-generation edits in watermarked LLM
          outputs. Instead of only asking whether a text is watermarked, our detector asks where
          suspicious local modifications may have occurred.
        </p>
        <div className="heroActions">
          <a className="button primary" href="#results">View results</a>
          <a className="button secondary" href="#demo">Preview walkthrough</a>
        </div>
      </div>
      <div className="heroPanel" aria-label="Pipeline summary">
        <div className="pipelineNode">Watermarked generation</div>
        <div className="pipelineArrow">{"->"}</div>
        <div className="pipelineNode warning">Sparse edit</div>
        <div className="pipelineArrow">{"->"}</div>
        <div className="pipelineNode">ECC detector</div>
        <div className="pipelineArrow">{"->"}</div>
        <div className="pipelineNode accent">Suspicious blocks</div>
      </div>
    </section>
  );
}

function Motivation() {
  return (
    <section className="section split">
      <div>
        <p className="eyebrow">Motivation</p>
        <h2>Watermark detection is not enough when edits are local.</h2>
      </div>
      <div className="bodyText">
        <p>
          Existing watermark detectors largely focus on document- or segment-level attribution:
          deciding whether a text was generated by an LLM. In practice, however, a watermarked
          response may be locally edited after generation while the overall watermark signal remains
          detectable.
        </p>
        <p>
          Small edits can change factuality, certainty, stance, or source attribution. Our goal is
          local integrity checking: given only the observed edited text and the watermark key, identify
          suspicious watermark blocks and provide candidate edit locations for downstream review.
        </p>
      </div>
    </section>
  );
}

function Method() {
  return (
    <section id="method" className="section">
      <div className="sectionHeader">
        <p className="eyebrow">Method overview</p>
        <h2>Embedding local ECC structure into generated text</h2>
        <p>
          The watermark maps tokens into structural bits and boundary anchors. Local blocks are
          constrained by a feasible codeword set C = V_a(n) intersect H, combining VT sensitivity to
          insertion/deletion edits with Hamming parity sensitivity to substitutions.
        </p>
      </div>

      <div className="figureGrid">
        <figure>
          <img src="./assets/watermark_pipeline.png" alt="Watermark embedding pipeline" />
          <figcaption>Watermark embedding pipeline.</figcaption>
        </figure>
        <figure>
          <img src="./assets/decode_pipeline.png" alt="ECC decoding and localization pipeline" />
          <figcaption>Decoding and edit-localization pipeline.</figcaption>
        </figure>
      </div>

      <div className="methodGrid">
        {methodSteps.map((step) => (
          <article className="methodCard" key={step.title}>
            <h3>{step.title}</h3>
            <p>{step.text}</p>
          </article>
        ))}
      </div>
    </section>
  );
}

function Results() {
  return (
    <section id="results" className="section results">
      <div className="sectionHeader">
        <p className="eyebrow">Results</p>
        <h2>Block-level detection and localization under post-generation edits</h2>
        <p>
          We evaluate mixed insertion, deletion, and substitution attacks across edit rates and edit
          budgets. The approximate-hard setting uses delta = 20; weaker bias settings expose the
          robustness-distortion tradeoff.
        </p>
      </div>

      <div className="resultCards">
        {resultCards.map((card) => (
          <article className="resultCard" key={card.label}>
            <span>{card.label}</span>
            <strong>{card.value}</strong>
            <p>{card.detail}</p>
          </article>
        ))}
      </div>

      <div className="plotGrid">
        <figure>
          <img src="./assets/tpr_vs_edit_rate_by_k.png" alt="Block-level TPR by edit rate" />
          <figcaption>Block-level TPR under increasing edit rates and edit budgets.</figcaption>
        </figure>
        <figure>
          <img src="./assets/far_vs_edit_rate_by_k.png" alt="Block-level FAR by edit rate" />
          <figcaption>Block-level FAR under increasing edit rates and edit budgets.</figcaption>
        </figure>
      </div>

      <div className="comparison">
        <h3>LLM-guided sparse edits</h3>
        <p>
          Beyond random synthetic edits, we also run a question-aware LLM-guided editing study.
          Source answers are generated from English LFQA prompts using Qwen3-8B with the soft ECC
          watermark at delta = 5. The editor then proposes structured sparse edit instructions under
          benign and malicious motivations, and the program applies those edits deterministically to
          preserve exact block-level ground truth.
        </p>
        <p>
          This setting is intentionally closer to semantic risk assessment: LFQA questions make the
          answer content more meaningful, and stronger source generations make claim distortion,
          stance shift, and source-spoofing edits easier to interpret.
        </p>
        <div className="miniTable" role="table" aria-label="LLM-guided sparse edit detection">
          <div role="row" className="tableHead">
            <span>Edit type</span>
            <span>Cases</span>
            <span>Block TPR</span>
            <span>Block FAR</span>
            <span>Cov.</span>
          </div>
          <div role="row">
            <span>Overall</span>
            <span>226</span>
            <span>0.7712</span>
            <span>0.4888</span>
            <span>0.3925</span>
          </div>
          <div role="row">
            <span>Benign</span>
            <span>95</span>
            <span>0.7198</span>
            <span>0.4839</span>
            <span>0.4248</span>
          </div>
          <div role="row">
            <span>Malicious</span>
            <span>131</span>
            <span>0.8099</span>
            <span>0.4922</span>
            <span>0.3692</span>
          </div>
        </div>
        <p className="tableNote">
          Cov. denotes candidate edit-location coverage. These results summarize the latest
          Qwen3/LFQA sparse-edit run; the detector identifies structural edit evidence rather than
          deciding whether an edit is benign or malicious.
        </p>
      </div>
    </section>
  );
}

const demoSteps = [
  "Source answer",
  "Sparse edit",
  "Bucket view",
  "ECC decoding",
  "Localized alarm",
];

function InteractiveDemo() {
  const [exampleIndex, setExampleIndex] = useState(0);
  const [stepIndex, setStepIndex] = useState(0);
  const example = demoExamples[exampleIndex];
  const primaryFlag = useMemo(
    () => example.flaggedBlocks.find((block) => block.isGroundTruthEdited) ?? example.flaggedBlocks[0],
    [example],
  );

  return (
    <section id="demo" className="section demo">
      <div className="sectionHeader">
        <p className="eyebrow">Interactive walkthrough</p>
        <h2>Precomputed edit-localization replay</h2>
        <p>
          This walkthrough replays real examples from the latest LLM-guided sparse-edit run. It does
          not run a live model in the browser; instead, it shows the saved token buckets, structural
          symbols, detector parse, and localized block alarms produced by the evaluation pipeline.
        </p>
      </div>

      <div className="demoSelector" aria-label="Choose a precomputed example">
        {demoExamples.map((item, idx) => (
          <button
            className={idx === exampleIndex ? "selectorChip active" : "selectorChip"}
            key={item.id}
            onClick={() => {
              setExampleIndex(idx);
              setStepIndex(0);
            }}
          >
            <span>Example {idx + 1}</span>
            {item.title}
          </button>
        ))}
      </div>

      <div className="demoStage">
        <aside className="demoRail">
          {demoSteps.map((step, idx) => (
            <button
              className={idx === stepIndex ? "railStep active" : idx < stepIndex ? "railStep done" : "railStep"}
              key={step}
              onClick={() => setStepIndex(idx)}
            >
              <span>{idx + 1}</span>
              {step}
            </button>
          ))}
        </aside>

        <div className="demoCanvas">
          <div className="demoMeta">
            <span>Sequence {example.sequenceIndex}</span>
            <span>{example.motivation.replace("_", " ")}</span>
            <span>{example.intentLabel}</span>
          </div>

          <div className="questionCard">
            <strong>Question</strong>
            <p>{example.question}</p>
          </div>

          <div className="stepViewport">
              <div className="stepPanels" style={{ transform: `translateX(-${stepIndex * 100}%)` }}>
                <SourcePanel example={example} />
                <EditPanel example={example} />
                <BucketPanel example={example} />
                <DecodePanel block={primaryFlag} />
                <AlarmPanel example={example} />
              </div>
          </div>

          <div className="demoControls">
            <button onClick={() => setStepIndex(Math.max(0, stepIndex - 1))} disabled={stepIndex === 0}>
              Previous
            </button>
            <div className="progressDots">
              {demoSteps.map((step, idx) => (
                <button
                  aria-label={step}
                  className={idx === stepIndex ? "dot active" : "dot"}
                  key={step}
                  onClick={() => setStepIndex(idx)}
                />
              ))}
            </div>
            <button
              onClick={() => setStepIndex(Math.min(demoSteps.length - 1, stepIndex + 1))}
              disabled={stepIndex === demoSteps.length - 1}
            >
              Next
            </button>
          </div>
        </div>
      </div>
    </section>
  );
}

function SourcePanel({ example }) {
  return (
    <article className="stepPanel">
      <PanelHeader label="Step 1" title="Start from a watermarked LFQA answer" />
      <TextCompare
        leftTitle="Watermarked source answer"
        leftText={example.sourceAnswer}
        rightTitle="Edited answer preview"
        rightText={example.editedAnswer}
        mutedRight
      />
      <MetricStrip example={example} />
    </article>
  );
}

function EditPanel({ example }) {
  return (
    <article className="stepPanel">
      <PanelHeader label="Step 2" title="Show the edited sequence and the local edit motives" />
      <HighlightedAnswer text={example.editedAnswer} edits={example.edits} />
      <div className="editTraceGrid">
        {example.edits.map((edit, idx) => (
          <div className="editTraceCard" key={`${edit.op}-${edit.anchor}-${idx}`}>
            <span className="editOp">{edit.op}</span>
            <h3>
              {edit.originalText || "(gap)"} {"->"} {edit.newContent}
            </h3>
            <p>{edit.reason}</p>
            <div className="traceLine">
              <span>token/gap {edit.anchor}</span>
              <span>source block {edit.anchorBlock ?? "?"}</span>
              <span>detector block {edit.detectorBlock ?? "?"}</span>
            </div>
          </div>
        ))}
      </div>
    </article>
  );
}

function BucketPanel({ example }) {
  return (
    <article className="stepPanel">
      <PanelHeader label="Step 3" title="Trace each edit into the watermark structure" />
      <p className="panelText">
        Each edited token is first mapped to a vocabulary bucket. Bucket 0 and 1 become payload bits
        inside an ECC block; bucket 2 is a boundary anchor that closes a block. The detector later
        parses this structural sequence and checks whether each block still looks like a feasible
        VT+Hamming codeword.
      </p>
      <div className="bucketLegend">
        <span className="bucketMini bucket0">B0 = payload bit 0</span>
        <span className="bucketMini bucket1">B1 = payload bit 1</span>
        <span className="bucketMini bucket2">B2 = boundary anchor</span>
      </div>
      <div className="structureTraceList">
        {example.edits.map((edit, idx) => (
          <div className="structureTraceCard" key={`${edit.op}-${edit.anchor}-${idx}`}>
            <div className="traceSource">
              <span className="traceLabel">Edited token</span>
              <strong>{edit.newContent || edit.originalText || "(inserted text)"}</strong>
              <small>
                token/gap {edit.anchor}; source surface "{edit.anchorToken?.surface ?? "n/a"}"
              </small>
            </div>
            <div className="traceArrow">{"->"}</div>
            <TraceNode
              label="Bucket"
              value={`B${edit.anchorToken?.bucketId ?? "?"}`}
              detail={edit.bucketMeaning}
              tone={`bucket${edit.anchorToken?.bucketId}`}
            />
            <div className="traceArrow">{"->"}</div>
            <TraceNode
              label="ECC block"
              value={`block ${edit.anchorBlock ?? "?"}`}
              detail={`structural index ${edit.anchorToken?.structuralIndex ?? "?"}`}
            />
            <div className="traceArrow">{"->"}</div>
            <TraceNode
              label="Detector alarm"
              value={`block ${edit.detectorBlock ?? "?"}`}
              detail={`payload distance ${edit.payloadDistance ?? "n/a"}`}
              tone="alarmNode"
            />
            <p className="traceReason">{edit.reason}</p>
            <p className="traceSnippet">
              Detector snippet: <mark>{edit.detectorSnippet || "n/a"}</mark>
            </p>
          </div>
        ))}
      </div>
    </article>
  );
}

function TraceNode({ label, value, detail, tone = "" }) {
  return (
    <div className={`traceNode ${tone}`}>
      <span>{label}</span>
      <strong>{value}</strong>
      <small>{detail}</small>
    </div>
  );
}

function HighlightedAnswer({ text, edits }) {
  const pieces = buildHighlightedPieces(text, edits);
  return (
    <div className="highlightedAnswer">
      <strong>Edited answer with local modifications highlighted</strong>
      <p>
        {pieces.map((piece, idx) =>
          piece.edit ? (
            <mark className={`editMark mark${piece.editIndex % 3}`} key={`${piece.text}-${idx}`}>
              {piece.text}
            </mark>
          ) : (
            <span key={`${piece.text}-${idx}`}>{piece.text}</span>
          ),
        )}
      </p>
    </div>
  );
}

function buildHighlightedPieces(text, edits) {
  const ranges = [];
  for (const [editIndex, edit] of edits.entries()) {
    const needle = (edit.newContent || edit.originalText || "").trim();
    if (!needle) continue;
    let start = text.indexOf(needle);
    while (start >= 0 && ranges.some((range) => start < range.end && start + needle.length > range.start)) {
      start = text.indexOf(needle, start + needle.length);
    }
    if (start >= 0) {
      ranges.push({ start, end: start + needle.length, editIndex });
    }
  }
  ranges.sort((a, b) => a.start - b.start);
  const pieces = [];
  let cursor = 0;
  for (const range of ranges) {
    if (range.start > cursor) pieces.push({ text: text.slice(cursor, range.start) });
    pieces.push({ text: text.slice(range.start, range.end), edit: true, editIndex: range.editIndex });
    cursor = range.end;
  }
  if (cursor < text.length) pieces.push({ text: text.slice(cursor) });
  return pieces;
}

function DecodePanel({ block }) {
  return (
    <article className="stepPanel">
      <PanelHeader label="Step 4" title={`Decode parsed block ${block.blockId}`} />
      <p className="panelText">
        The detector parses the observed structural sequence into ECC blocks, then compares each
        observed payload segment to the nearest feasible VT+Hamming codeword. This block exceeds
        the tolerance threshold and is raised as an alarm.
      </p>
      <div className="decodeGrid">
        <CodeVector title="Observed structural segment" values={block.observedSegment} tone="observed" />
        <CodeVector title="Nearest decoded codeword" values={block.decodedCodeword} tone="decoded" />
        <div className="distanceCard">
          <span>Payload distance</span>
          <strong>{block.payloadDistance ?? "n/a"}</strong>
          <p>Boundary: {block.boundaryState ?? "unknown"}</p>
        </div>
      </div>
      <CandidateList locations={block.candidateLocations} />
    </article>
  );
}

function AlarmPanel({ example }) {
  return (
    <article className="stepPanel">
      <PanelHeader label="Step 5" title="Localize suspicious blocks in natural language" />
      <div className="blockMap">
        {Array.from({ length: 12 }, (_, blockId) => {
          const predicted = example.predictedBlocks.includes(blockId);
          const edited = example.gtBlocks.includes(blockId);
          return (
            <div
              className={predicted ? (edited ? "blockCell hit" : "blockCell alarm") : edited ? "blockCell missed" : "blockCell"}
              key={blockId}
            >
              {blockId}
            </div>
          );
        })}
      </div>
      <div className="snippetGrid">
        {example.flaggedBlocks.map((block) => (
          <div className={block.isGroundTruthEdited ? "snippetCard hit" : "snippetCard"} key={block.blockId}>
            <span>Block {block.blockId}</span>
            <p>{block.snippet}</p>
          </div>
        ))}
      </div>
      <p className="legendText">
        Green blocks are detector alarms that overlap true edited blocks; orange blocks are detector
        alarms outside the edited locations; red outline marks a true edited block missed by this example.
      </p>
    </article>
  );
}

function PanelHeader({ label, title }) {
  return (
    <div className="panelHeader">
      <span>{label}</span>
      <h3>{title}</h3>
    </div>
  );
}

function TextCompare({ leftTitle, leftText, rightTitle, rightText, mutedRight = false }) {
  return (
    <div className="textCompare">
      <div>
        <strong>{leftTitle}</strong>
        <p>{leftText}</p>
      </div>
      <div className={mutedRight ? "mutedPreview" : ""}>
        <strong>{rightTitle}</strong>
        <p>{rightText}</p>
      </div>
    </div>
  );
}

function MetricStrip({ example }) {
  return (
    <div className="metricStrip">
      <span>GT edited blocks: {example.gtBlocks.join(", ")}</span>
      <span>Predicted alarms: {example.predictedBlocks.join(", ")}</span>
      <span>TPR {example.metrics.blockTpr.toFixed(2)}</span>
      <span>FAR {example.metrics.blockFar.toFixed(2)}</span>
    </div>
  );
}

function CodeVector({ title, values, tone }) {
  return (
    <div className="codeVector">
      <strong>{title}</strong>
      <div>
        {(values ?? []).map((value, idx) => (
          <span className={`bit ${tone}`} key={`${title}-${idx}`}>
            {value}
          </span>
        ))}
      </div>
    </div>
  );
}

function CandidateList({ locations }) {
  return (
    <div className="candidateList">
      <strong>Candidate edit-location set</strong>
      <div>
        {(locations ?? []).map((loc, idx) => (
          <span key={`${loc[0]}-${loc[1]}-${idx}`}>
            {loc[0]} {loc[1]}
          </span>
        ))}
      </div>
    </div>
  );
}

function Citation() {
  return (
    <section id="citation" className="section citation">
      <div className="sectionHeader">
        <p className="eyebrow">Paper and references</p>
        <h2>Citation</h2>
      </div>
      <pre>{`@misc{local_integrity_ecc_watermark,
  title  = {Local Integrity Checking for Watermarked LLM Outputs via Error-Correcting Codes},
  author = {Anonymous Authors},
  year   = {2026}
}`}</pre>
      <h3>Selected references</h3>
      <ul>
        {references.map((ref) => (
          <li key={ref}>{ref}</li>
        ))}
      </ul>
    </section>
  );
}

export default App;
